name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      
      - name: Build Docker Image
        run: |
          docker build -t MedHachami/my-app \
            --build-arg VITE_apiKey=${{ secrets.VITE_API_KEY }} \
            --build-arg VITE_authDomain=${{ secrets.VITE_AUTH_DOMAIN }} \
            --build-arg VITE_projectId=${{ secrets.VITE_PROJECT_ID }} \
            --build-arg VITE_storageBucket=${{ secrets.VITE_STORAGE_BUCKET }} \
            --build-arg VITE_messagingSenderId=${{ secrets.VITE_MESSAGING_SENDER_ID }} \
            --build-arg VITE_appId=${{ secrets.VITE_APP_ID }} \
            .
      
      - name: Publish Image to Docker Hub
        run: docker push MedHachami/my-app:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull MedHachami/my-app:latest 
      
      - name: Delete Old Container
        run: docker rm -f my-app-container
      
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name my-app-container MedHachami/my-app
